export interface Artisan {
    id: string;
    name: string;
    craftType: string;
    location: string;
    state: string;
    story: string;
    experience: number;
    avatar: string;
    gallery: string[];
    rating: number;
    productsCount: number;
    followers: number;
}

export interface Product {
    id: string;
    artisanId: string;
    artisanName: string;
    name: string;
    description: string;
    price: number;
    originalPrice?: number;
    category: string;
    images: string[];
    story: string;
    materials: string[];
    rating: number;
    reviews: number;
    inStock: boolean;
    featured: boolean;
}

export interface DashboardStats {
    totalViews: number;
    totalLikes: number;
    totalOrders: number;
    totalRevenue: number;
    viewsChange: number;
    likesChange: number;
    ordersChange: number;
    revenueChange: number;
}

export const mockArtisans: Artisan[] = [
    {
        id: 'a1',
        name: 'Lakshmi Devi',
        craftType: 'Pottery',
        location: 'Jaipur',
        state: 'Rajasthan',
        story: 'For five generations, my family has shaped clay into vessels that carry both water and our cultural legacy. Each piece I create echoes the pink city sunsets that inspired my grandmother\'s first pottery wheel.',
        experience: 25,
        avatar: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=200&h=200&fit=crop&crop=face',
        gallery: [
            'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&h=400&fit=crop',
            'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&h=400&fit=crop',
            'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&h=400&fit=crop',
        ],
        rating: 4.9,
        productsCount: 34,
        followers: 1250,
    },
    {
        id: 'a2',
        name: 'Ravi Kumar',
        craftType: 'Woodcraft',
        location: 'Saharanpur',
        state: 'Uttar Pradesh',
        story: 'I learned woodcarving from my father when I was just seven. Every stroke of the chisel tells a story of patience and devotion. My rosewood boxes have traveled to homes across 15 countries.',
        experience: 30,
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
        gallery: [
            '/ravi-woodcraft.png',
            'https://images.unsplash.com/photo-1611486212557-88be5ff027dc?w=600&h=400&fit=crop',
        ],
        rating: 4.8,
        productsCount: 28,
        followers: 980,
    },
    {
        id: 'a3',
        name: 'Meera Patel',
        craftType: 'Handloom',
        location: 'Ahmedabad',
        state: 'Gujarat',
        story: 'Patola silk weaving is an art that demands years of dedication. I weave dreams into fabric, with patterns that have been passed down for centuries through my family\'s legacy in Patan.',
        experience: 18,
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face',
        gallery: [
            'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600&h=400&fit=crop',
            'https://images.unsplash.com/photo-1606722590583-6951b5ea92ad?w=600&h=400&fit=crop',
        ],
        rating: 4.9,
        productsCount: 42,
        followers: 2100,
    },
    {
        id: 'a4',
        name: 'Abdul Rashid',
        craftType: 'Embroidery',
        location: 'Lucknow',
        state: 'Uttar Pradesh',
        story: 'Chikankari embroidery is the heartbeat of Lucknow. My needle dances on muslin fabric creating intricate patterns that Mughal emperors once cherished. Each stitch is a meditation in itself.',
        experience: 22,
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
        gallery: [
            'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=400&fit=crop',
        ],
        rating: 4.7,
        productsCount: 56,
        followers: 1800,
    },
    {
        id: 'a5',
        name: 'Priya Sharma',
        craftType: 'Jewelry',
        location: 'Jaipur',
        state: 'Rajasthan',
        story: 'Kundan and Meenakari jewelry making runs in my veins. I transform raw stones and metals into wearable art that celebrates Indian heritage with every sparkle and color.',
        experience: 15,
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face',
        gallery: [
            '/priya-jewelry.jpg',
        ],
        rating: 4.8,
        productsCount: 63,
        followers: 3200,
    },
    {
        id: 'a6',
        name: 'Sunita Kumari',
        craftType: 'Painting',
        location: 'Madhubani',
        state: 'Bihar',
        story: 'Madhubani paintings are more than art—they are prayers on paper. My mother taught me to paint stories of gods, nature, and love using natural colors from flowers and bark.',
        experience: 20,
        avatar: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=200&h=200&fit=crop&crop=face',
        gallery: [
            'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=400&fit=crop',
        ],
        rating: 4.9,
        productsCount: 38,
        followers: 2800,
    },
    {
        id: 'a7',
        name: 'Suresh Ram',
        craftType: 'Bamboo Craft',
        location: 'Guwahati',
        state: 'Assam',
        story: 'In Assam, bamboo is life. I treat every stalk with respect, transforming it into light fixtures that bring the warmth of our forests into modern homes.',
        experience: 15,
        avatar: 'https://images.unsplash.com/photo-1540569014015-19a7ee504e3a?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=600&h=400&fit=crop'],
        rating: 4.8,
        productsCount: 22,
        followers: 750,
    },
    {
        id: 'a8',
        name: 'Zarina Begum',
        craftType: 'Embroidery',
        location: 'Srinagar',
        state: 'Kashmir',
        story: 'My hands carry the winter stories of Srinagar in every needle pull. Kashmiri Pashmina and Aari work are the legacy of my ancestors, woven with patience.',
        experience: 28,
        avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&h=400&fit=crop'],
        rating: 5.0,
        productsCount: 15,
        followers: 1600,
    },
    {
        id: 'a9',
        name: 'Mohan Das',
        craftType: 'Metalwork',
        location: 'Puri',
        state: 'Odisha',
        story: 'Dhokra art is as old as civilization itself. I use the lost-wax casting technique to create metal spirits that celebrate our tribal heritage.',
        experience: 35,
        avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1590732823619-3733075bf712?w=600&h=400&fit=crop'],
        rating: 4.7,
        productsCount: 45,
        followers: 890,
    },
    {
        id: 'a10',
        name: 'Anjali Devi',
        craftType: 'Painting',
        location: 'Raghurajpur',
        state: 'West Bengal',
        story: 'Pattachitra is not just painting; it\'s storytelling on cloth. Every scroll I create is a journey through Indian mythology and regional folklore.',
        experience: 12,
        avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2a00?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=600&h=400&fit=crop'],
        rating: 4.9,
        productsCount: 18,
        followers: 1100,
    },
    {
        id: 'a11',
        name: 'Vikram Singh',
        craftType: 'Jewelry',
        location: 'Pratapgarh',
        state: 'Rajasthan',
        story: 'Thewa jewelry is the secret of the Rajpurohit family. I am honored to preserve this unique technique of fusing gold patterns onto colored glass.',
        experience: 19,
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1515562141589-67f0d569b6fc?w=600&h=400&fit=crop'],
        rating: 4.8,
        productsCount: 26,
        followers: 2400,
    },
    {
        id: 'a12',
        name: 'Sita Mani',
        craftType: 'Handloom',
        location: 'Kanchipuram',
        state: 'Tamil Nadu',
        story: 'Woven for queens, Kanchipuram silk is the gold standard of Indian textiles. My loom breathes color into every silk thread and silver zari.',
        experience: 32,
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=600&h=400&fit=crop'],
        rating: 4.9,
        productsCount: 52,
        followers: 3100,
    },
    {
        id: 'a13',
        name: 'Rajeshwari Bai',
        craftType: 'Pottery',
        location: 'Ukhrul',
        state: 'Manipur',
        story: 'Longpi pottery uses no wheel. We shape the black clay and serpentinite rock by hand, creating unique pieces that are as durable as they are beautiful.',
        experience: 40,
        avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&h=400&fit=crop'],
        rating: 5.0,
        productsCount: 12,
        followers: 1450,
    },
    {
        id: 'a14',
        name: 'Arjun Munda',
        craftType: 'Woodcraft',
        location: 'Ranchi',
        state: 'Jharkhand',
        story: 'My woodcarvings celebrate the tribal spirits of Jharkhand. Each mask and totem is a guardian of our forest traditions and tribal identity.',
        experience: 14,
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1611486212557-88be5ff027dc?w=600&h=400&fit=crop'],
        rating: 4.6,
        productsCount: 34,
        followers: 520,
    },
    {
        id: 'a15',
        name: 'Fatima Bi',
        craftType: 'Embroidery',
        location: 'Lucknow',
        state: 'Uttar Pradesh',
        story: 'Zardozi is the embroidery of kings. I use gold and silver metallic threads to create patterns that shimmer with the glory of the Mughal era.',
        experience: 25,
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&h=400&fit=crop'],
        rating: 4.8,
        productsCount: 42,
        followers: 1900,
    },
    {
        id: 'a16',
        name: 'Gopinath',
        craftType: 'Metalwork',
        location: 'Bidar',
        state: 'Karnataka',
        story: 'Bidriware is the art of inlaying silver on black metal. I take pride in keeping this 500-year-old Deccani tradition alive in my small workshop.',
        experience: 30,
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&h=400&fit=crop'],
        rating: 4.9,
        productsCount: 28,
        followers: 1300,
    },
    {
        id: 'a17',
        name: 'Neelam',
        craftType: 'Bamboo Craft',
        location: 'Wayanad',
        state: 'Kerala',
        story: 'Wayanad bamboo is exceptionally strong. I create eco-friendly lifestyle products that prove traditional materials are the key to a sustainable future.',
        experience: 10,
        avatar: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&h=400&fit=crop'],
        rating: 4.7,
        productsCount: 19,
        followers: 980,
    },
    {
        id: 'a18',
        name: 'Shanti',
        craftType: 'Painting',
        location: 'Palghar',
        state: 'Maharashtra',
        story: 'Warli art uses simple geometric shapes to represent the circle of life. My paintings reflect the joy and harmony of our tribal community.',
        experience: 22,
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
        gallery: ['https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=400&fit=crop'],
        rating: 4.9,
        productsCount: 31,
        followers: 1750,
    },
];

export const mockProducts: Product[] = [
    {
        id: 'p1',
        artisanId: 'a1',
        artisanName: 'Lakshmi Devi',
        name: 'Blue Pottery Vase — Floral Motif',
        description: 'A stunning handcrafted blue pottery vase featuring traditional Rajasthani floral motifs. Made using age-old techniques passed down through generations, this piece brings the warmth of Indian heritage into your home.',
        price: 2499,
        originalPrice: 3499,
        category: 'pottery',
        images: [
            'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&h=600&fit=crop',
            'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&h=600&fit=crop',
        ],
        story: 'This vase was inspired by the blue tiles of Jaipur\'s City Palace. Each flower painted on it represents a blessing for the home it adorns.',
        materials: ['Clay', 'Natural dyes', 'Quartz stone powder'],
        rating: 4.8,
        reviews: 124,
        inStock: true,
        featured: true,
    },
    {
        id: 'p2',
        artisanId: 'a2',
        artisanName: 'Ravi Kumar',
        name: 'Rosewood Carved Jewelry Box',
        description: 'Exquisite hand-carved rosewood jewelry box with intricate floral and geometric patterns. A perfect blend of utility and artistry from the master woodcarvers of Saharanpur.',
        price: 3999,
        originalPrice: 5499,
        category: 'woodcraft',
        images: [
            '/rosewood-box.png',
        ],
        story: 'Carved from a single block of aged rosewood, this box took 15 days to complete. Each pattern tells a story of the forests of Uttarakhand.',
        materials: ['Rosewood', 'Brass hinges', 'Velvet lining'],
        rating: 4.9,
        reviews: 87,
        inStock: true,
        featured: true,
    },
    {
        id: 'p3',
        artisanId: 'a3',
        artisanName: 'Meera Patel',
        name: 'Patola Silk Dupatta — Double Ikat',
        description: 'Authentic Patan Patola silk dupatta woven using the ancient double ikat technique. Each piece takes approximately 4-6 months to weave, making it a true collector\'s item.',
        price: 15999,
        originalPrice: 22000,
        category: 'handloom',
        images: [
            '/patola-dupatta.png',
        ],
        story: 'This dupatta carries 700 years of Gujarati weaving tradition. The geometric patterns symbolize prosperity and good fortune.',
        materials: ['Pure silk', 'Natural dyes', 'Gold zari thread'],
        rating: 5.0,
        reviews: 45,
        inStock: true,
        featured: true,
    },
    {
        id: 'p4',
        artisanId: 'a4',
        artisanName: 'Abdul Rashid',
        name: 'Chikankari Anarkali Kurta',
        description: 'Elegantly hand-embroidered Chikankari Anarkali kurta on fine muslin fabric. Features intricate shadow work and tepchi stitches that showcase the finest Lucknowi craftsmanship.',
        price: 4599,
        category: 'embroidery',
        images: [
            'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=600&fit=crop',
        ],
        story: 'Each Chikankari piece is a labor of love, taking 20 days of meticulous hand embroidery. This kurta features 32 different types of traditional stitches.',
        materials: ['Muslin fabric', 'Cotton thread', 'Natural wash'],
        rating: 4.7,
        reviews: 156,
        inStock: true,
        featured: false,
    },
    {
        id: 'p5',
        artisanId: 'a5',
        artisanName: 'Priya Sharma',
        name: 'Kundan Meenakari Necklace Set',
        description: 'Magnificent Kundan Meenakari necklace set featuring uncut polki diamonds set in pure gold-plated silver. The reverse side showcases beautiful Meenakari enamel work in vibrant colors.',
        price: 8999,
        originalPrice: 12999,
        category: 'jewelry',
        images: [
            '/kundan-necklace.png',
        ],
        story: 'This necklace draws inspiration from Mughal-era royal jewelry. Each stone is hand-set using traditional lac filling technique perfected over centuries.',
        materials: ['Gold-plated silver', 'Kundan stones', 'Meenakari enamel', 'Pearls'],
        rating: 4.8,
        reviews: 203,
        inStock: true,
        featured: true,
    },
    {
        id: 'p6',
        artisanId: 'a6',
        artisanName: 'Sunita Kumari',
        name: 'Madhubani Tree of Life Painting',
        description: 'Original Madhubani painting depicting the sacred Tree of Life, symbolizing the connection between earth and heaven. Painted using natural colors on handmade paper.',
        price: 5499,
        category: 'painting',
        images: [
            'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=600&fit=crop',
        ],
        story: 'The Tree of Life is a sacred symbol in Mithila culture. This painting uses colors derived from turmeric, indigo, flowers, and charcoal — just as my ancestors did.',
        materials: ['Handmade paper', 'Natural pigments', 'Bamboo pen'],
        rating: 4.9,
        reviews: 67,
        inStock: true,
        featured: true,
    },
    {
        id: 'p7',
        artisanId: 'a1',
        artisanName: 'Lakshmi Devi',
        name: 'Terracotta Tea Cup Set (6 pieces)',
        description: 'Set of 6 handcrafted terracotta tea cups with traditional Rajasthani designs. Each cup is kiln-fired and food-safe, bringing an earthy elegance to your tea time.',
        price: 1299,
        originalPrice: 1899,
        category: 'pottery',
        images: [
            'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&h=600&fit=crop',
        ],
        story: 'Tea tastes different in clay cups — my grandmother always said it carries the flavor of the earth. These cups are shaped to cool your chai to the perfect temperature.',
        materials: ['Terracotta clay', 'Natural glaze', 'Food-safe coating'],
        rating: 4.6,
        reviews: 289,
        inStock: true,
        featured: false,
    },
    {
        id: 'p8',
        artisanId: 'a2',
        artisanName: 'Ravi Kumar',
        name: 'Handcarved Wooden Wall Panel',
        description: 'Ornate hand-carved wooden wall panel featuring traditional Indian mandala designs. Perfect as a statement piece for living rooms or entryways.',
        price: 12999,
        category: 'woodcraft',
        images: [
            '/wooden-panel.png',
        ],
        story: 'This mandala panel took 45 days of continuous carving. The design represents the cosmos and the unity of all life — a meditation captured in wood.',
        materials: ['Teak wood', 'Hand tools', 'Natural oil finish'],
        rating: 4.9,
        reviews: 34,
        inStock: true,
        featured: false,
    },
    {
        id: 'p9',
        artisanId: 'a7',
        artisanName: 'Suresh Ram',
        name: 'Modern Bamboo Lamp Shade',
        description: 'Eco-friendly bamboo lamp shade with a modern minimalist design. Handcrafted by master artisans from Assam using sustainable bamboo.',
        price: 1899,
        originalPrice: 2499,
        category: 'bamboo',
        images: ['https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=600&h=600&fit=crop&q=80'],
        story: 'This lamp shade is designed to cast beautiful geometric patterns of light and shadow, inspired by the sunset through bamboo groves.',
        materials: ['Muli Bamboo', 'Natural varnish', 'Cotton cord'],
        rating: 4.8,
        reviews: 42,
        inStock: true,
        featured: true,
    },
    {
        id: 'p10',
        artisanId: 'a8',
        artisanName: 'Zarina Begum',
        name: 'Pure Pashmina Embroidered Shawl',
        description: 'Authentic Kashmiri Pashmina shawl with exquisite hand-embroidered floral patterns. Soft, warm, and timelessly elegant.',
        price: 24500,
        originalPrice: 32000,
        category: 'embroidery',
        images: ['https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&h=600&fit=crop&q=80'],
        story: 'Woven from the finest wool of Changthangi goats, this shawl took three months of patient hand embroidery to complete.',
        materials: ['Pure Pashmina Wool', 'Silk thread', 'Natural dyes'],
        rating: 5.0,
        reviews: 18,
        inStock: true,
        featured: true,
    },
    {
        id: 'p11',
        artisanId: 'a9',
        artisanName: 'Mohan Das',
        name: 'Dhokra Tribal Elephant Pair',
        description: 'Traditional Dhokra metal art elephant pair, made using the ancient lost-wax casting technique. A symbol of strength and heritage.',
        price: 3499,
        category: 'metalwork',
        images: ['https://images.unsplash.com/photo-1590732823619-3733075bf712?w=600&h=600&fit=crop&q=80'],
        story: 'In our tradition, elephants are guardians of the home. These metal figures carry the raw energy of our tribal rituals.',
        materials: ['Bell metal', 'Beeswax', 'Clay mold'],
        rating: 4.7,
        reviews: 56,
        inStock: true,
        featured: false,
    },
    {
        id: 'p12',
        artisanId: 'a10',
        artisanName: 'Anjali Devi',
        name: 'Krishna Leela Pattachitra Scroll',
        description: 'Vibrant Pattachitra painting on seasoned cloth depicting scenes from the life of Lord Krishna. A masterpiece of Odishan art.',
        price: 6999,
        originalPrice: 8500,
        category: 'painting',
        images: ['https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=600&h=600&fit=crop&q=80'],
        story: 'Every color in this scroll is derived from stones, shells, and leaves. It tells the story of divine love and cosmic harmony.',
        materials: ['Cotton cloth', 'Stone pigments', 'Conch shell white'],
        rating: 4.9,
        reviews: 24,
        inStock: true,
        featured: true,
    },
    {
        id: 'p13',
        artisanId: 'a11',
        artisanName: 'Vikram Singh',
        name: 'Thewa Gold Pendant — Radha Krishna',
        description: 'Exquisite Thewa jewelry pendant featuring 24k gold foil fused onto emerald green glass. A royal Rajasthani treasure.',
        price: 18500,
        category: 'jewelry',
        images: ['https://images.unsplash.com/photo-1515562141589-67f0d569b6fc?w=600&h=600&fit=crop&q=80'],
        story: 'This secret art family has protected Thewa for 200 years. Each piece is a miniature gold forest set in glass.',
        materials: ['24k Gold foil', 'Belgian glass', 'Sterling silver base'],
        rating: 4.8,
        reviews: 31,
        inStock: true,
        featured: false,
    },
    {
        id: 'p14',
        artisanId: 'a12',
        artisanName: 'Sita Mani',
        name: 'Kanchipuram Silk Bridal Saree',
        description: 'Luxurious Kanchipuram silk saree with heavy gold zari borders and traditional temple motifs. The ultimate in Indian elegance.',
        price: 42000,
        originalPrice: 55000,
        category: 'handloom',
        images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=600&fit=crop&q=80'],
        story: 'Woven for a lifetime of memories, this saree carries the heritage of South India in its heavy silk and pure gold zari.',
        materials: ['Pure Mulberry Silk', 'Gold Zari', 'Natural dves'],
        rating: 4.9,
        reviews: 74,
        inStock: true,
        featured: true,
    },
    {
        id: 'p15',
        artisanId: 'a13',
        artisanName: 'Rajeshwari Bai',
        name: 'Longpi Black Stone Dinner Set',
        description: 'Hand-shaped Longpi pottery dinner set including 2 plates and 2 bowls. Naturally non-stick and rich in minerals.',
        price: 5999,
        category: 'pottery',
        images: ['https://images.unsplash.com/photo-1599727402511-2098d5a2da1e?w=600&h=600&fit=crop&q=80'],
        story: 'Cooking and eating in Longpi stone brings the minerals of our mountains to your food. No machines, just earth and fire.',
        materials: ['Serpentinite rock', 'Weathered clay', 'Cane accents'],
        rating: 5.0,
        reviews: 12,
        inStock: true,
        featured: true,
    },
    {
        id: 'p16',
        artisanId: 'a14',
        artisanName: 'Arjun Munda',
        name: 'Tribal Guardian Wooden Mask',
        description: 'Striking hand-carved tribal mask from Jharkhand, painted with traditional motifs. A unique cultural statement piece.',
        price: 2499,
        category: 'woodcraft',
        images: ['https://images.unsplash.com/photo-1611486212557-88be5ff027dc?w=600&h=600&fit=crop&q=80'],
        story: 'This mask represents the forest protector. It is carved from reclaimed wood during the Sarhul festival season.',
        materials: ['Gamhar wood', 'Tribal pigments', 'Jute rope'],
        rating: 4.6,
        reviews: 19,
        inStock: true,
        featured: false,
    },
    {
        id: 'p17',
        artisanId: 'a15',
        artisanName: 'Fatima Bi',
        name: 'Zardozi Embroidered Silk Clutch',
        description: 'Exquisite silk clutch bag with heavy Zardozi metallic embroidery and semi-precious stone accents.',
        price: 3899,
        originalPrice: 4999,
        category: 'embroidery',
        images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&h=600&fit=crop&q=80'],
        story: 'A touch of royal Lucknow to carry with you. Each stitch is a celebration of the era of Nawabs.',
        materials: ['Silk velvet', 'Metallic wire', 'Faux pearls'],
        rating: 4.8,
        reviews: 63,
        inStock: true,
        featured: true,
    },
    {
        id: 'p18',
        artisanId: 'a16',
        artisanName: 'Gopinath',
        name: 'Bidriware Silver Inlay Vase',
        description: 'Elegant zinc and copper alloy vase with intricate pure silver wire inlay patterns in traditional Deccani style.',
        price: 8499,
        category: 'metalwork',
        images: ['https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&h=600&fit=crop&q=80'],
        story: 'The black color comes from the special soil of Bidar Fort. The silver inlay represents the light of the moon on a dark night.',
        materials: ['Zinc-Copper alloy', 'Pure Silver', 'Bidar soil paste'],
        rating: 4.9,
        reviews: 25,
        inStock: true,
        featured: false,
    },
    {
        id: 'p19',
        artisanId: 'a17',
        artisanName: 'Neelam',
        name: 'Eco-friendly Bamboo Planter Set',
        description: 'Set of 3 minimalist bamboo planters for indoor gardens. Biodegradable and beautifully natural.',
        price: 1299,
        originalPrice: 1699,
        category: 'bamboo',
        images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&h=600&fit=crop&q=80'],
        story: 'Bring the Kerala backwaters to your balcony. These planters are designed to let your plants breathe naturally.',
        materials: ['Treated Bamboo', 'Coconut husk lining', 'Eco-seal'],
        rating: 4.7,
        reviews: 89,
        inStock: true,
        featured: true,
    },
    {
        id: 'p20',
        artisanId: 'a18',
        artisanName: 'Shanti',
        name: 'Warli Celebration Wall Art',
        description: 'Traditional Warli painting on handmade paper, depicting a village celebration. A celebration of community life.',
        price: 2199,
        category: 'painting',
        images: ['https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=600&fit=crop&q=80'],
        story: 'My paintings use only white rice paste on an ocher background. They show how we are all connected in the circle of the Tarpa dance.',
        materials: ['Handmade paper', 'Rice paste', 'Natural ocher'],
        rating: 4.9,
        reviews: 43,
        inStock: true,
        featured: false,
    },
    {
        id: 'p21',
        artisanId: 'a1',
        artisanName: 'Lakshmi Devi',
        name: 'Floral Blue Pottery Plate',
        description: 'Hand-painted decorative blue pottery plate from Jaipur. Perfect for wall decor or serving dry snacks.',
        price: 1599,
        category: 'pottery',
        images: ['https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&h=600&fit=crop&q=80'],
        story: 'Each petal is painted with a brush made of squirrel hair, just as my father taught me.',
        materials: ['Quartz stone powder', 'Glass', 'Cobalt blue dye'],
        rating: 4.8,
        reviews: 112,
        inStock: true,
        featured: false,
    },
    {
        id: 'p22',
        artisanId: 'a2',
        artisanName: 'Ravi Kumar',
        name: 'Teak Wood Lotus Coaster Set',
        description: 'Set of 6 hand-carved teak wood coasters featuring delicate lotus patterns.',
        price: 999,
        originalPrice: 1499,
        category: 'woodcraft',
        images: ['https://images.unsplash.com/photo-1611486212557-88be5ff027dc?w=600&h=600&fit=crop&q=80'],
        story: 'Wood lives even after it is carved. These coasters bring the warmth of teak to your table.',
        materials: ['Seasoned Teak Wood', 'Natural oil finish'],
        rating: 4.7,
        reviews: 215,
        inStock: true,
        featured: false,
    },
    {
        id: 'p23',
        artisanId: 'a3',
        artisanName: 'Meera Patel',
        name: 'Banarasi Silk Heritage Scarf',
        description: 'Elegant Banarasi silk scarf with traditional butidar patterns and zari border.',
        price: 2899,
        category: 'handloom',
        images: ['https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=600&h=600&fit=crop&q=80'],
        story: 'A piece of Kashi heritage for the modern woman. Woven with the same care as our wedding sarees.',
        materials: ['Silk-Cotton blend', 'Gold-plated thread'],
        rating: 4.9,
        reviews: 58,
        inStock: true,
        featured: false,
    },
    {
        id: 'p24',
        artisanId: 'a4',
        artisanName: 'Abdul Rashid',
        name: 'Hand-embroidered Wedding Juttis',
        description: 'Traditional leather juttis with heavy gold-thread embroidery and beadwork.',
        price: 1999,
        originalPrice: 2499,
        category: 'embroidery',
        images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&h=600&fit=crop&q=80'],
        story: 'Walk like royalty. These juttis are crafted to be soft on the feet and heavy on heritage.',
        materials: ['Genuine Leather', 'Tilla work', 'Beads'],
        rating: 4.6,
        reviews: 87,
        inStock: true,
        featured: false,
    },
    {
        id: 'p25',
        artisanId: 'a5',
        artisanName: 'Priya Sharma',
        name: 'Silver Filigree Peacock Earrings',
        description: 'Delicate handcrafted silver filigree earrings featuring a peacock motif. Traditional Odishan artistry.',
        price: 2499,
        category: 'jewelry',
        images: ['https://images.unsplash.com/photo-1515562141589-67f0d569b6fc?w=600&h=600&fit=crop&q=80'],
        story: 'Silver filigree is like web of light. I weave thin silver wires into patterns that dance with you.',
        materials: ['925 Sterling Silver', 'Hand-drawn wires'],
        rating: 4.8,
        reviews: 45,
        inStock: true,
        featured: false,
    },
    {
        id: 'p26',
        artisanId: 'a6',
        artisanName: 'Sunita Kumari',
        name: 'Miniature Madhubani Keepsake Box',
        description: 'Small hand-painted wooden box with detailed Madhubani bird and fish patterns.',
        price: 899,
        category: 'painting',
        images: ['https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=600&fit=crop&q=80'],
        story: 'A tiny home for your treasures, painted with my favorite nature stories.',
        materials: ['MDF Wood', 'Acrylics', 'Varnish'],
        rating: 4.7,
        reviews: 134,
        inStock: true,
        featured: false,
    },
];

export const mockDashboardStats: DashboardStats = {
    totalViews: 12458,
    totalLikes: 3847,
    totalOrders: 156,
    totalRevenue: 485600,
    viewsChange: 12.5,
    likesChange: 8.3,
    ordersChange: 15.2,
    revenueChange: 22.1,
};

export const mockCulturalStories = [
    {
        id: 'cs1',
        title: 'The Living Art of Madhubani',
        region: 'Bihar',
        excerpt: 'Born from the walls of ancient Mithila homes, Madhubani painting transforms everyday surfaces into vibrant tapestries of mythology and nature.',
        image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&h=400&fit=crop',
    },
    {
        id: 'cs2',
        title: 'The Blue Pottery of Jaipur',
        region: 'Rajasthan',
        excerpt: 'A craft born from Turko-Persian roots, Jaipur\'s blue pottery uses no clay — only quartz stone powder, glass, and multani mitti create its distinctive turquoise beauty.',
        image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&h=400&fit=crop',
    },
    {
        id: 'cs3',
        title: 'Kashmiri Pashmina — The Diamond Fiber',
        region: 'Kashmir',
        excerpt: 'Woven from the finest cashmere wool of Changthangi goats, each Pashmina shawl represents months of painstaking handwork in the valleys of Kashmir.',
        image: 'https://images.unsplash.com/photo-1606722590583-6951b5ea92ad?w=800&h=400&fit=crop',
    },
];
